### ISSUE TITLE
Sometimes using third-party library styles will be replaced leading to error

### ISSUE THREAD

**Issue by GuangChao-Yu** [springuper/postcss-viewport-units#3]
It is recommended to add a third-party library that can be shielded, or to shield the configuration options of node_modules

**Comment by springuper** [comment]
thanks for your feedback, but could you explain it more clearly? what do you require this feature, and how it can help you?

**Comment by wujie520303** [comment]
when you use antd-mobile will trigger warning: (Emitted value instead of an instance of Error) postcss-viewport-units: /xxx/sos/sos-h5/node_modules/antd-mobile/lib/button/style/index.css:69:3: 'html:not([data-scale]) .am-button-primary::before' already has a 'content' property, give up to overwrite it.

my .postcssrc.js config is:
```
module.exports = {
  "plugins": {
    "postcss-devtools": {},
    "postcss-import": {},
    "postcss-url": {},
    "postcss-aspect-ratio-mini": {}, 
      "postcss-write-svg": {
        utf8: false
      },
      "postcss-cssnext": {},
      "postcss-px-to-viewport": {
        viewportWidth: 750,
        viewportHeight: 1334,
        unitPrecision: 3,
        viewportUnit: 'vw',
        selectorBlackList: ['.ignore', '.hairlines'],  // (Array) The selectors to ignore and leave as px.
        minPixelValue: 1, 
        mediaQuery: false 
      }, 
    "postcss-viewport-units": {},
    // "postcss-browser-reporter": {},
    "postcss-reporter": {},
    "cssnano": {
      preset: "advanced",
      autoprefixer: false,
      "postcss-zindex": false
    },
  }
}

```

**Comment by springuper** [comment]
see https://github.com/springuper/postcss-viewport-units/issues/5#issuecomment-380997516. if you still have problem, please reopen this issue. close it first for now.

**Comment by springuper** [comment]
BTW, you can use `filterRule` to filter out the css rules you want to apply the viewpoint unit hack: create `content` declaration. see README and test file for details.

**Comment by codeXian** [comment]
@springuper  how to use filterRule to avoid thrid-party console this warning

**Comment by codeXian** [comment]
@springuper  can you give me the demo

**Comment by springuper** [comment]
@codeXian you can check this test case: https://github.com/springuper/postcss-viewport-units/blob/master/test/index.js#L43.
actually, the plugin's source code is pretty simple: https://github.com/springuper/postcss-viewport-units/blob/master/index.js#L14.
let me know if you still have problems. and i'm glad that you check the above codes and know how it works, furthermore, you can create a PR if you find another solution to meet your needs.
