### ISSUE TITLE
postcss-viewport-units with font-awesome

### ISSUE THREAD

**Issue by anotherWill** [springuper/postcss-viewport-units#5]
Hi. 
postcss-viewport-units will create content property and when I use font-awesome, It occured one warning.
like `.head-icon::before {
      content: '\e911';
      color: #333;
      font: 44px/1 icons;
      display: inline-block;
    }`

webpack warning:
WARNING in ./node_modules/css-loader??ref--5-2!./node_modules/postcss-loader/lib??ref--5-3!./src/assets/css/main.css
    (Emitted value instead of an instance of Error) postcss-viewport-units: /Applications/project/mobile/hwr/src/assets/css/common/nav.css:68:7: '.head-icon::before' already has a 'conten
t' property, give up to overwrite it.

**Comment by springuper** [comment]
yes, this is intended. if the rule has some declarations with viewport units or `calc`, and `content`, this warning is shown.
https://github.com/springuper/postcss-viewport-units/blob/master/index.js#L30

**Comment by springuper** [comment]
close it since there is no reply. please reopen it if you still have problems.
