### ISSUE TITLE
Base64 image cannot be displayed in iphonex

### ISSUE THREAD

**Issue by taomas** [springuper/postcss-viewport-units#6]
use the plugin, Base64 image cannot be displayed in iphonex.
but if i remove the plugin, displayed in iphonex is ok.

**Comment by springuper** [comment]
could you give an example? that would be very helpful.

**Comment by taomas** [comment]
can i get the element target name in `filterRule` params? it's seem if i ignore image element by `filterRule`, the bug will fixed.

but i only get selector in filterRule option, can i ignore all image element use the option?

**Comment by lmw6412036** [comment]
@wendaosanshou 
@springuper 

Note: The content hack may not work well on <img> and other replaced elements, even though it should compute to content: normal; on regular elements. If you find yourself in such a situation, this may be a way out:
```h
img {
  content: normal !important;
}
```

**Comment by taomas** [comment]
thx
