### ISSUE TITLE
How to avoid third party libraries being converted

### ISSUE THREAD

**Issue by cloudGrin** [springuper/postcss-viewport-units#8]
How to avoid third party libraries being converted

**Comment by cloudGrin** [comment]
(Emitted value instead of an instance of Error) postcss-viewport-units: /Users/wangwenhan/workspace/work/juzhu/h-phone/node_modules/mint-ui/lib/switc
h/style.css:39:1: '.mint-switch-core::after, .mint-switch-core::before' already has a 'content' property, give up to overwrite it.

**Comment by springuper** [comment]
can you try `filterRule` option? there should be file information in `rule` argument, see this test case:
https://github.com/springuper/postcss-viewport-units/blob/master/test/index.js#L47.

**Comment by springuper** [comment]
@Wangwenhan please try the 0.1.6 version, there is a new `filterFile` option.
