### ISSUE TITLE
Is there a optional param `silence` to control whether show the warning? 

### ISSUE THREAD

**Issue by dancon** [springuper/postcss-viewport-units#9]
I know it will print a warning when there is already a content, and i can do nothing, but it's very noisy when compilation is in watch mode, especially enable HMR.

so， maybe i can specify a optional param `silence: true` to close it.

**Comment by dancon** [comment]
I have commit a PR, please take time to review it.[PR](https://github.com/springuper/postcss-viewport-units/pull/10)

**Comment by DevinZhong** [comment]
Hey, I find a solution to avoid warnings about `content` property. Just use the `filterRule` option as below:
```
'postcss-viewport-units': {
  filterRule: rule => rule.nodes.findIndex(i => i.prop === 'content') === -1
}
```

The `filterRule` option is very flexible, you can have a try. @dancon

**Comment by dancon** [comment]
> Hey, I find a solution to avoid warnings about `content` property. Just use the `filterRule` option as below:
> 
> ```
> 'postcss-viewport-units': {
>   filterRule: rule => rule.nodes.findIndex(i => i.prop === 'content') === -1
> }
> ```
> The `filterRule` option is very flexible, you can have a try. @dancon

It also work to me. Thank you ~

**Comment by springuper** [comment]
close this issue since we have merged the related PR.
